# Generated by Django 5.2.14 on 2026-05-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookNow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('button_text', models.CharField(default='Book Appointment', max_length=50)),
                ('image', models.ImageField(upload_to='booknow/')),
            ],
        ),
    ]
