# Generated by Django 5.2.14 on 2026-05-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savapp', '0002_booking_delete_booknow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.CharField(choices=[('Bridal Makeup', 'Bridal Makeup'), ('Hair Styling', 'Hair Styling'), ('Hair Spa', 'Hair Spa'), ('Facial Treatment', 'Facial Treatment'), ('Nail Art', 'Nail Art'), ('Skin Care', 'Skin Care')], max_length=50),
        ),
    ]
